2014/11/27 20:36:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in /var/www/blog/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/blog/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/blog/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/blog/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/blog/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/blog/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /var/www/blog/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /var/www/blog/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/blog/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/blog/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/blog/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/blog/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/blog/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/blog/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/blog/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /var/www/blog/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/blog/blog2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/blog/blog2/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/blog/blog2/index.php?r=gii/default/index
---
